baseURL = 'https://hanlyjiang.github.io/'
languageCode = 'zh-cn'
title = '清水池塘'
theme = "PaperMod"


# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# 菜单（顶部导航）
[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 1
  pre = "<i class='fas fa-home'></i>"    # 在文本前加图标

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 2
  pre = "<i class='fas fa-tags'></i>"


#[[menu.main]]
#  identifier = "categories"
#  name = "分类"
#  url = "/categories/"
#  weight = 3

[[menu.main]]
  identifier = "tags"
  name = "标签"
  url = "/tags/"
  weight = 4

[[menu.main]]
  identifier = "search"
  name = "搜索"
  url = "/search/"
  weight = 5


[params]
  author = "野生莲藕"
  defaultTheme = "auto"
  showReadingTime = true
  showToc = true
  comments = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  TocOpen = false
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  ShowShareButtons = false
  ShowBreadCrumbs = true

  # 搜索设置（PaperMod 会根据此开关生成 /search/ 页面）
  [params.search]
    enabled = true
    # engine = "fuse"   # 可选：fuse / lunr（按需开启）

  # 归档设置（PaperMod 有时使用 params.archive）
  [params.archive]
    enabled = true

  [params.assets]
    disableHLJS = false
    disableFontAwesome = false
  